### ISSUE TITLE
Particle coordinate is nan

### ISSUE THREAD

**Issue by SSchott** [MiaoLab20/DBMD#1]
Hi,
Thanks for the code for testing DBMD. It sounds like a  very cool concept, but while the included test is running just fine, I wanted to stress test it on a multimeric protein with explicit solvent (339,775 atoms), and at the beginning of the Equilibration Stage, I get a `Particle coordinate is nan` exception. I can continue the sim with the conventional MD integrator included though, so it seems like there might be something off with the DL integrator that causes one of the atoms to go off. Have you ever tried it on bigger systems as this one? Here is the gamd-restart file that is generated immediately before the exception:

```
#Parameters Values(kcal/mol)
(0)Trained Steps:   1000
(1)Boosted VminD:   0.0
(2)Boosted VmaxD:   0.0
(3)Boosted VfinalD: 0.0
(4)Average k0D: 1.0
(5)Final k0D:   1.0
(6)Boosted VminP:   -848049.6961671403
(7)Boosted VmaxP:   -842835.1472383881
(8)Boosted VfinalP: -846513.0081714058
(9)Average k0P: 1.0
(10)Final k0P:  1.0
```

**Comment by SSchott** [comment]
Ok :man_facepalming:  , I was printing an additional column and that caused the wrong parsing and 0 Boosted potential. I made a pull request to force pandas not to assume an index column #2

**Comment by hungd238** [comment]
Glad it was resolved and thank you very much for the commit / contribution. Somehow I don't get any automatic notifications for your thread. Guess I will need to check the package more often to not miss any of the requests / comments.
