### ISSUE TITLE
Does the RestartFreq need to be small?

### ISSUE THREAD

**Issue by amin-sagar** [MiaoLab20/DBMD#4]
Hello.
Thanks for this amazing work.
I am running an explicit solvent DBMD and experiencing a significant slowdown compared to classical MD.
I am wondering if the relatively small values of 100 for cmdRestartFreq, ebprepRestartFreq and ebRestartFreq are required to gather enough data points or can they be increased to a larger value?
Are there some general recommendations for these values based on your experience?

Best,
Amin.

**Comment by hungd238** [comment]
Hello Amin,

Thank you for bringing this up. We did observe that the simulation speeds decreased significantly with low restart frequencies in OpenMM. It's probably the best to use a restart frequency of 500-1000 for your simulation, as long as you can generate at least 10,000 simulation frames for the deep learning analysis.

All the best,
Hung

**Comment by amin-sagar** [comment]
Thanks Hung.
This is very helpful. I will test with restart frequencies of 500 and 1000. I am quite sure this will lead to some increase in simulation speed.
Best,
Amin.
