### ISSUE TITLE
Extremely high values of total boost

### ISSUE THREAD

**Issue by amin-sagar** [MiaoLab20/DBMD#5]
Hello.
I tried my first simulation with DBMD. I am getting very large values of Total Boost.
My restart,dat file looks like this
```
#Parameters     Values(kcal/mol)
(0)Steps:       250000000
(1)Boosted VminD:       -15.50736801118285
(2)Boosted VmaxD:       67.93761390117112
(3)DihedralRefEnergy:   67.93761390117112
(4)Final DihedralBoost: 8.552234274717506
(5)Final k0D:   1.0
(6)Boosted VminP:       -33975.71221024916
(7)Boosted VmaxP:       -18073.626585170263
(8)TotalRefEnergy:      -18073.626585170263
(9)Final TotalBoost:    1997.254225520609
(10)Final k0P:  0.2674758994026407
```
My simParams.py file is as follows
```
parmFile = "../test-bonded_solv.parm7"
crdFile = "../test-bonded_solv_forDBMD.rst7"
simType = "explicit"    # "explicit", "protein.implicit", "RNA.implicit"

nbCutoff = 9.0      # if "explicit"
temperature = 300

ntcmd = 10000000
cmdRestartFreq = 100

ncycebprepstart, ncycebprepend = 0, 1
ntebpreppercyc = 2500000
ebprepRestartFreq = 100

ncycebstart, ncycebend = 0, 3
ntebpercyc = 2500000
ebRestartFreq = 100

ncycprodstart, ncycprodend = 0, 4
ntprodpercyc = 250000000
prodRestartFreq = 500

refEP_factor, refED_factor = 1.0, 1.0      # between 0 and 1
```
I set refEP_factor and refED_factor to 1 because I thought these are the appropriate values for explicit solvent simulations.

My log file looks like this.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/AMIN~1.SAG/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/AMIN~1.SAG/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ntwx | total_nstep | Total-Energy | Dihedral-Energy | Total-Force-Weight | Dihedral-Force-Weight | Total-Boost | Dihedral-Boost | Total-Harmonic-Force-Constant | Dihedral-Harmonic-Force-Constant | Minimum-Total-Energy | Maximum-Total-Energy | Minimum-Dihedral-Energy | Maximum-Dihedral-Energy | Total-Reference-Energy | Dihedral-Reference-Energy
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
500 | 500 | -33591.43937 | 16.34396103 | 0.738987638 | 0.381704547 | 2025.170485 | 15.95006048 | 0.267475899 | 1 | -33975.71221 | -18073.62659 | -15.50736801 | 67.9376139 | -18073.62659 | 67.9376139
500 | 1000 | -33593.29037 | 31.90343649 | 0.738956504 | 0.568168432 | 2025.653648 | 7.780347673 | 0.267475899 | 1 | -33975.71221 | -18073.62659 | -15.50736801 | 67.9376139 | -18073.62659 | 67.9376139
500 | 1500 | -33656.90339 | 36.34594686 | 0.737886521 | 0.621407228 | 2042.293445 | 5.980188405 | 0.267475899 | 1 | -33975.71221 | -18073.62659 | -15.50736801 | 67.9376139 | -18073.62659 | 67.9376139
500 | 2000 | -33622.1877 | 27.64135474 | 0.738470446 | 0.517091882 | 2033.204131 | 9.729695336 | 0.267475899 | 1 | -33975.71221 | -18073.62659 | -15.50736801 | 67.9376139 | -18073.62659 | 67.9376139
500 | 2500 | -33572.59722 | 28.61878703 | 0.739304566 | 0.528805376 | 2020.255437 | 9.263409919 | 0.267475899 | 1 | -33975.71221 | -18073.62659 | -15.50736801 | 67.9376139 | -18073.62659 | 67.9376139

</body>

</html>

I prepared my system using AmberTools with amber ff15ipq force field.
Can you see anything obviously wrong with my setup.
I would be really grateful for your help.
Best,
Amin.

**Comment by amin-sagar** [comment]
Update:
I just observed that the Total Boost value keeps increasing with iterations of equilibration.

equil-0.restart.dat
```
#Parameters     Values(kcal/mol)
(0)Steps:       2500000
(1)Boosted VminD:       -43.7630312392634
(2)Boosted VmaxD:       14.43173643735809
(3)DihedralRefEnergy:   14.43173643735809
(4)Final DihedralBoost: 8.917178426430281
(5)Final k0D:   1.0
(6)Boosted VminP:       -36544.09772650155
(7)Boosted VmaxP:       -35655.81559381528
(8)TotalRefEnergy:      -35641.511742211624
(9)Final TotalBoost:    8.177890555760996
(10)Final k0P:  0.9841523668075728
```
equil-1.restart.dat
```
#Parameters     Values(kcal/mol)
(0)Steps:       2500000
(1)Boosted VminD:       -30.738064709402632
(2)Boosted VmaxD:       41.96622494757745
(3)DihedralRefEnergy:   41.96622494757745
(4)Final DihedralBoost: 6.193636788000536
(5)Final k0D:   1.0
(6)Boosted VminP:       -35854.04335269658
(7)Boosted VmaxP:       -33570.67849879103
(8)TotalRefEnergy:      -33088.7716984325
(9)Final TotalBoost:    81.67579305682911
(10)Final k0P:  0.8257289479623373
```
equil-2.restart.dat
```
#Parameters     Values(kcal/mol)
(0)Steps:       2500000
(1)Boosted VminD:       -15.50736801118285
(2)Boosted VmaxD:       67.93761390117112
(3)DihedralRefEnergy:   67.93761390117112
(4)Final DihedralBoost: 9.953120195886349
(5)Final k0D:   1.0
(6)Boosted VminP:       -33975.71221024916
(7)Boosted VmaxP:       -18073.626585170263
(8)TotalRefEnergy:      -18073.626585170263
(9)Final TotalBoost:    2005.2044408191816
(10)Final k0P:  0.2674758994026407
```
Maybe, this can help in understanding what the problem is.

**Comment by hungd238** [comment]
Thank you for your testings. I admire my own software more now that the system has not blown up with 2000+ kcal/mol boosts. Even though the refEP_factor and refED_factor can be set anywhere between 0 and 1, I suggest you set these values somewhere around 0.05-0.25 first. This value serves to set the upper limits of the reference energy, and apparently you don't want the maximum reference energy to be double (1+1) of the maximum potential energy. See below explanation for refEP_factor:

refEP_factor: The reference total potential energy factor (𝜂P) for applying total boost potentials. This parameter, valued between 0 and 1, is introduced to avoid exceedingly large reference potential energy. The upper limit for
the reference total potential energy 𝐸P is 𝑉maxP + 𝜂P*|𝑉maxP|.

**Comment by amin-sagar** [comment]
Yes, it's amazing that the system doesn't blow up. In fact, I sample the folded conformations starting from the completely misfolded structure even at these boost values.
I tried reducing the reference values and I am starting to suspect if there is another problem.
I tried setting both to 0.1 and I get
equil-prep-0.restart.dat
```
(1)Boosted VminD:	-75.460598072176
(2)Boosted VmaxD:	1.840700382940172
(3)DihedralRefEnergy:	1.840700382940172
(4)Final DihedralBoost:	3.85853552228135
(5)Final k0D:	1.0
(6)Boosted VminP:	-37922.17492535432
(7)Boosted VmaxP:	-36294.65295367206
(8)TotalRefEnergy:	-36294.65295367206
(9)Final TotalBoost:	5.283988620426344
(10)Final k0P:	1.0
```
equil-0.restart.dat
```
(1)Boosted VminD:	-43.93050593126344
(2)Boosted VmaxD:	17.38697438577393
(3)DihedralRefEnergy:	17.38697438577393
(4)Final DihedralBoost:	4.116659806067236
(5)Final k0D:	1.0
(6)Boosted VminP:	-36570.13441388205
(7)Boosted VmaxP:	-34628.316113426
(8)TotalRefEnergy:	-34628.316113426
(9)Final TotalBoost:	68.92331273037216
(10)Final k0P:	0.3350168638782635
```
Current values (Simulation still running)
```
(1)Boosted VminD:	-15.715106723413411
(2)Boosted VmaxD:	61.92730672044918
(3)DihedralRefEnergy:	61.92730672044918
(4)Final DihedralBoost:	4.50778142303166
(5)Final k0D:	1.0
(6)Boosted VminP:	-33641.94069973291
(7)Boosted VmaxP:	-30039.295754158626
(8)TotalRefEnergy:	-30039.295754158626
(9)Final TotalBoost:	391.1238092795764
(10)Final k0P:	0.5349235409651297
```
I tried further reducing the reference values to 0.05
equil-prep-0.restart.dat
```
(1)Boosted VminD:	-71.80003499893567
(2)Boosted VmaxD:	8.877162495717036
(3)DihedralRefEnergy:	8.877162495717036
(4)Final DihedralBoost:	5.647580503927847
(5)Final k0D:	1.0
(6)Boosted VminP:	-37937.74017392029
(7)Boosted VmaxP:	-36322.0672503392
(8)TotalRefEnergy:	-36322.0672503392
(9)Final TotalBoost:	6.1713738690747055
(10)Final k0P:	1.0
```
equil-0.restart.dat
```
(1)Boosted VminD:	-44.6832704270547
(2)Boosted VmaxD:	41.87114562404771
(3)DihedralRefEnergy:	41.87114562404771
(4)Final DihedralBoost:	12.067892698746649
(5)Final k0D:	1.0
(6)Boosted VminP:	-36568.98419877689
(7)Boosted VmaxP:	-32828.899665042605
(8)TotalRefEnergy:	-31793.703468885662
(9)Final TotalBoost:	217.47485311619985
(10)Final k0P:	0.7832177300745778
```
Current values (Simulation still running)
```
(1)Boosted VminD:	-24.18453880295471
(2)Boosted VmaxD:	44.92993473322852
(3)DihedralRefEnergy:	44.92993473322852
(4)Final DihedralBoost:	5.906566095523729
(5)Final k0D:	1.0
(6)Boosted VminP:	-33360.974519044576
(7)Boosted VmaxP:	-32108.038319561718
(8)TotalRefEnergy:	-32108.038319561718
(9)Final TotalBoost:	123.576444987359
(10)Final k0P:	0.4364577876386488
```
The boosts are still too large.
Can you think of anything else that could be wrong?
I will try even lower values and report back.
Thanks.

**Comment by amin-sagar** [comment]
Tried 0.01 for both reference energies. The boost look in the range I am used to from GaMD. But I am not sure if everything is correct if the reference energies have to be set to so low.
The values are different stages are as follows.
equil-0.restart.dat
```
(1)Boosted VminD:	-44.799060712125055
(2)Boosted VmaxD:	15.992049733265864
(3)DihedralRefEnergy:	15.992049733265864
(4)Final DihedralBoost:	4.286726811830378
(5)Final k0D:	1.0
(6)Boosted VminP:	-36543.84378290691
(7)Boosted VmaxP:	-35728.9856876999
(8)TotalRefEnergy:	-35724.03503965878
(9)Final TotalBoost:	5.8553101969686185
(10)Final k0P:	0.9939612158544434
```
equil-1.restart.dat
```
(1)Boosted VminD:	-34.961109635478905
(2)Boosted VmaxD:	23.073639514113474
(3)DihedralRefEnergy:	23.073639514113474
(4)Final DihedralBoost:	8.830197181433125
(5)Final k0D:	1.0
(6)Boosted VminP:	-35925.22224849008
(7)Boosted VmaxP:	-35312.01095551655
(8)TotalRefEnergy:	-35304.94221964719
(9)Final TotalBoost:	4.538031705499505
(10)Final k0P:	0.9886039602426984
```
equil-2.restart.dat
```
(1)Boosted VminD:	-24.303060644671287
(2)Boosted VmaxD:	32.09221294687537
(3)DihedralRefEnergy:	32.09221294687537
(4)Final DihedralBoost:	4.536041113399042
(5)Final k0D:	1.0
(6)Boosted VminP:	-35492.84593395853
(7)Boosted VmaxP:	-34789.11871895201
(8)TotalRefEnergy:	-34748.59444509505
(9)Final TotalBoost:	12.431713760286742
(10)Final k0P:	0.9455502952115776
```

**Comment by hungd238** [comment]
Hi Amin,

Even though the refEP_factor = 0.01 (or the maximum of Etotal can only be 101% of maximum total potential energy), you still have upper-bound GaMD-equivalent (iEP = 2) enabled for your simulations based on this:

```
(7)Boosted VmaxP:	-34789.11871895201
(8)TotalRefEnergy:	-34748.59444509505
```
(You have lower-bound GaMD equivalent (iE = 1) when the RefEnergy = Vmax) As long as you can reach your simulation goal (seems like protein folding here), I think that should be fine. My sincere apologies for not responding to your comment sooner. I have some stuff to focus on at the moment.

Thank you for the further testings!
Hung

**Comment by hungd238** [comment]
On a side note, the reason I designed DBMD to run equilibration in multiple iterations is that users can select the restart point from an iteration that they feel comfortable with (based on boost statistics, some simulation analysis, etc.) and continue into production simulation. Therefore, you can select equil-0.rst and equil-0.restart.dat, for example, and run production simulations with them, not necessarily equil-2.rst and equil-2.restart.dat.

**Comment by amin-sagar** [comment]
Thanks a lot @hungd238.
I think I understand now that these values are reasonable.
Also, thanks for explaining about lower and upper bounds. I was wondering how these setting can be used with DBMD. If I understood correctly, this means that if the set both the reference energies to 0, I will switch to lower-bound mode. Is that correct?
And If I set one of them to 0 and the other one to a non-zero positive value then I can lower-bound on one and upper bound to the other. Similar to overwriting the iE value using iEP and iED in Amber?
Best,
Amin.

**Comment by hungd238** [comment]
Hi Amin,

The answer to your first question is yes. If you set both the reference energy factors to 0, you will definitely run your simulations to lower-bound modes. Your simulations may still run in lower-bound modes at higher values of reference energy factors though. However, the higher the reference energy factors, the less likely you will run your simulation in lower-bound modes (and the more likely you will get high boost values like you observed).

The answer to your second question is also yes. You can run the total boost in lower-bound and dihedral boost in upper-bound (and vice versa), depending on what value you define for the reference energy factors.

Sincerely,
Hung

**Comment by amin-sagar** [comment]
Thanks a lot @hungd238 
Best,
Amin.
