### ISSUE TITLE
about the DLGaMDSimulationIntegrator module 

### ISSUE THREAD

**Issue by c00jsw00** [MiaoLab20/DBMD#6]
Dear Sir ,
Could you tell me how to download the  DLGaMDSimulationIntegrator module?
Thanks 
YT

**Comment by hungd238** [comment]
Thank you very much for your interest. DLGaMDSimulationIntegrator is a python script included within the DBMD package: https://github.com/MiaoLab20/DBMD/blob/main/DLGaMDSimulationIntegrator.py. You just have to pull the whole github repository for DBMD, and everything should be included.

**Comment by c00jsw00** [comment]
Dear Sir,
Thanks a lot.  I have succeeded  to run the test case.
By the way, the version of tensorflow should be less than 2.12 .

**Comment by hungd238** [comment]
Thank you very much for pointing out the recommended version of tensorflow. I have not tested this extensively yet, but will include notes in the README file after my test.
